version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ./gradlew build --scan
artifacts:
  files:
    - 'auth-service-0.0.1-SNAPSHOT.jar'
  base-directory: 'build/libs'
