spring:
    main:
        allow-circular-references: true
    redis:
        host: localhost
        port: 6379
        timeout: 60000
    datasource:
        driver-class-name: org.postgresql.Driver
        password: Password
        url: jdbc:postgresql://127.0.0.1:5432/postgres?sslmode=disable
        username: postgres

app:
    email:
        registration:
            senderEmail: sriman456.singh@gmail.com
            regSubject: GIG Economy OTP for registration
            otpSubject: GIG Economy OTP for Login
            verificationUrl: http://localhost:8080/api/v1/confirm?otp=
            otpExpirationInHours: 24
        login:
            otp:
                otpExpirationInHours: 120
    jwt:
        jwtSecret: SecretKey
        jwtExpirationMs: 1800000

cloud:
    aws:
        region:
            static: ap-southeast-1
        credentials:
            access-key: AKIAXKKX7G5CV6XZ2JN2
            secret-key: 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

server:
    error:
        include-stacktrace:  


